//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSAuto.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSAuto.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string button_apply {
            get {
                return ResourceManager.GetString("button_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AK-47.
        /// </summary>
        public static string buyitem_ak47 {
            get {
                return ResourceManager.GetString("buyitem_ak47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUG.
        /// </summary>
        public static string buyitem_aug {
            get {
                return ResourceManager.GetString("buyitem_aug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWP.
        /// </summary>
        public static string buyitem_awp {
            get {
                return ResourceManager.GetString("buyitem_awp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CZ75-Auto.
        /// </summary>
        public static string buyitem_cz75auto {
            get {
                return ResourceManager.GetString("buyitem_cz75auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desert Eagle.
        /// </summary>
        public static string buyitem_deagle {
            get {
                return ResourceManager.GetString("buyitem_deagle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoy Grenade.
        /// </summary>
        public static string buyitem_decoy {
            get {
                return ResourceManager.GetString("buyitem_decoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defuse Kit.
        /// </summary>
        public static string buyitem_defusekit {
            get {
                return ResourceManager.GetString("buyitem_defusekit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual Berettas.
        /// </summary>
        public static string buyitem_dualberettas {
            get {
                return ResourceManager.GetString("buyitem_dualberettas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAMAS.
        /// </summary>
        public static string buyitem_famas {
            get {
                return ResourceManager.GetString("buyitem_famas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five Seven.
        /// </summary>
        public static string buyitem_fiveseven {
            get {
                return ResourceManager.GetString("buyitem_fiveseven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashbang.
        /// </summary>
        public static string buyitem_flashbang {
            get {
                return ResourceManager.GetString("buyitem_flashbang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G3SG1.
        /// </summary>
        public static string buyitem_g3sg1 {
            get {
                return ResourceManager.GetString("buyitem_g3sg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galil-AR.
        /// </summary>
        public static string buyitem_galilar {
            get {
                return ResourceManager.GetString("buyitem_galilar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glock-18.
        /// </summary>
        public static string buyitem_glock18 {
            get {
                return ResourceManager.GetString("buyitem_glock18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Explosive Grenade.
        /// </summary>
        public static string buyitem_he {
            get {
                return ResourceManager.GetString("buyitem_he", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kevlar &amp; Helmet.
        /// </summary>
        public static string buyitem_kevlarandhelmet {
            get {
                return ResourceManager.GetString("buyitem_kevlarandhelmet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kevlar Vest.
        /// </summary>
        public static string buyitem_kevlarvest {
            get {
                return ResourceManager.GetString("buyitem_kevlarvest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M249.
        /// </summary>
        public static string buyitem_m249 {
            get {
                return ResourceManager.GetString("buyitem_m249", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M4A1-S.
        /// </summary>
        public static string buyitem_m4a1s {
            get {
                return ResourceManager.GetString("buyitem_m4a1s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M4A4.
        /// </summary>
        public static string buyitem_m4a4 {
            get {
                return ResourceManager.GetString("buyitem_m4a4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC-10.
        /// </summary>
        public static string buyitem_mac10 {
            get {
                return ResourceManager.GetString("buyitem_mac10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAG-7.
        /// </summary>
        public static string buyitem_mag7 {
            get {
                return ResourceManager.GetString("buyitem_mag7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incendiary Grenade / Molotov.
        /// </summary>
        public static string buyitem_molotov {
            get {
                return ResourceManager.GetString("buyitem_molotov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP5-SD.
        /// </summary>
        public static string buyitem_mp5sd {
            get {
                return ResourceManager.GetString("buyitem_mp5sd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP7.
        /// </summary>
        public static string buyitem_mp7 {
            get {
                return ResourceManager.GetString("buyitem_mp7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP9.
        /// </summary>
        public static string buyitem_mp9 {
            get {
                return ResourceManager.GetString("buyitem_mp9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negev.
        /// </summary>
        public static string buyitem_negev {
            get {
                return ResourceManager.GetString("buyitem_negev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string buyitem_none {
            get {
                return ResourceManager.GetString("buyitem_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova.
        /// </summary>
        public static string buyitem_nova {
            get {
                return ResourceManager.GetString("buyitem_nova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P250.
        /// </summary>
        public static string buyitem_p250 {
            get {
                return ResourceManager.GetString("buyitem_p250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P90.
        /// </summary>
        public static string buyitem_p90 {
            get {
                return ResourceManager.GetString("buyitem_p90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PP-Bizon.
        /// </summary>
        public static string buyitem_ppbizon {
            get {
                return ResourceManager.GetString("buyitem_ppbizon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R8 Revolver.
        /// </summary>
        public static string buyitem_r8revolver {
            get {
                return ResourceManager.GetString("buyitem_r8revolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sawed-Off.
        /// </summary>
        public static string buyitem_sawedoff {
            get {
                return ResourceManager.GetString("buyitem_sawedoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCAR 20.
        /// </summary>
        public static string buyitem_scar20 {
            get {
                return ResourceManager.GetString("buyitem_scar20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SG 553.
        /// </summary>
        public static string buyitem_sg553 {
            get {
                return ResourceManager.GetString("buyitem_sg553", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoke Grenade.
        /// </summary>
        public static string buyitem_smoke {
            get {
                return ResourceManager.GetString("buyitem_smoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSG 08.
        /// </summary>
        public static string buyitem_ssg08 {
            get {
                return ResourceManager.GetString("buyitem_ssg08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tec-9.
        /// </summary>
        public static string buyitem_tec9 {
            get {
                return ResourceManager.GetString("buyitem_tec9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UMP-45.
        /// </summary>
        public static string buyitem_ump45 {
            get {
                return ResourceManager.GetString("buyitem_ump45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP-S / P2000.
        /// </summary>
        public static string buyitem_usp_s {
            get {
                return ResourceManager.GetString("buyitem_usp_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XM1014.
        /// </summary>
        public static string buyitem_xm1014 {
            get {
                return ResourceManager.GetString("buyitem_xm1014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeus x27.
        /// </summary>
        public static string buyitem_zeus {
            get {
                return ResourceManager.GetString("buyitem_zeus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use old mouse input technique.
        /// </summary>
        public static string ckbox_oldmouseinput {
            get {
                return ResourceManager.GetString("ckbox_oldmouseinput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use old screen capture technique.
        /// </summary>
        public static string ckbox_oldscreencapture {
            get {
                return ResourceManager.GetString("ckbox_oldscreencapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Button.
        /// </summary>
        public static string discord_addbutton {
            get {
                return ResourceManager.GetString("discord_addbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use template.
        /// </summary>
        public static string discord_createtemplate {
            get {
                return ResourceManager.GetString("discord_createtemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {CTScore} - CT side score.
        /// </summary>
        public static string discord_ctscore {
            get {
                return ResourceManager.GetString("discord_ctscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Deaths} - Current player deaths.
        /// </summary>
        public static string discord_deaths {
            get {
                return ResourceManager.GetString("discord_deaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {EnemyScore} - Enemy team score.
        /// </summary>
        public static string discord_enemyscore {
            get {
                return ResourceManager.GetString("discord_enemyscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {EnemyTeam} - Enemy team name.
        /// </summary>
        public static string discord_enemyteam {
            get {
                return ResourceManager.GetString("discord_enemyteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {FriendCode} - Your friencode.
        /// </summary>
        public static string discord_friendcode {
            get {
                return ResourceManager.GetString("discord_friendcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Gamemode} - The current match mode.
        /// </summary>
        public static string discord_gamemode {
            get {
                return ResourceManager.GetString("discord_gamemode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Kills} - Current player kills.
        /// </summary>
        public static string discord_kills {
            get {
                return ResourceManager.GetString("discord_kills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Label.
        /// </summary>
        public static string discord_label {
            get {
                return ResourceManager.GetString("discord_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Map} - The current match map.
        /// </summary>
        public static string discord_map {
            get {
                return ResourceManager.GetString("discord_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {MatchState} - Current match state.
        /// </summary>
        public static string discord_matchstate {
            get {
                return ResourceManager.GetString("discord_matchstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {MVPS} - Current player mvps.
        /// </summary>
        public static string discord_mvps {
            get {
                return ResourceManager.GetString("discord_mvps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {MyTeam} - Your current team.
        /// </summary>
        public static string discord_myteam {
            get {
                return ResourceManager.GetString("discord_myteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name} - Current player name.
        /// </summary>
        public static string discord_name {
            get {
                return ResourceManager.GetString("discord_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Button.
        /// </summary>
        public static string discord_removebutton {
            get {
                return ResourceManager.GetString("discord_removebutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may need to restart the app for changes to apply.
        /// </summary>
        public static string discord_restartneeded {
            get {
                return ResourceManager.GetString("discord_restartneeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string discord_result {
            get {
                return ResourceManager.GetString("discord_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RoundState} - Current round state.
        /// </summary>
        public static string discord_roundstate {
            get {
                return ResourceManager.GetString("discord_roundstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {SteamID} - Your steam id.
        /// </summary>
        public static string discord_steamid {
            get {
                return ResourceManager.GetString("discord_steamid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {TeamScore} - Your team score.
        /// </summary>
        public static string discord_teamscore {
            get {
                return ResourceManager.GetString("discord_teamscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {TScore} - T side score.
        /// </summary>
        public static string discord_tscore {
            get {
                return ResourceManager.GetString("discord_tscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Url.
        /// </summary>
        public static string discord_url {
            get {
                return ResourceManager.GetString("discord_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The custom weapon has already been selected.
        /// </summary>
        public static string error_alreadycontainscustom {
            get {
                return ResourceManager.GetString("error_alreadycontainscustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred!, would you like to send a crash report?.
        /// </summary>
        public static string error_appcrashed {
            get {
                return ResourceManager.GetString("error_appcrashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t add &apos;+exec csautobindcommandsender.cfg&apos; to launch options, please add it manually.
        /// </summary>
        public static string error_bindlaunchoption {
            get {
                return ResourceManager.GetString("error_bindlaunchoption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create files, logs and debug stuff wont be saved.
        /// </summary>
        public static string error_createfiles {
            get {
                return ResourceManager.GetString("error_createfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a button template.
        /// </summary>
        public static string error_discordselecttemplate {
            get {
                return ResourceManager.GetString("error_discordselecttemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid inputs.
        /// </summary>
        public static string error_entervalid {
            get {
                return ResourceManager.GetString("error_entervalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load the changelog, please check your internet connection.
        /// </summary>
        public static string error_loadchangelog {
            get {
                return ResourceManager.GetString("error_loadchangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load colors for button, be aware that auto accept wont work!.
        /// </summary>
        public static string error_loadcolors {
            get {
                return ResourceManager.GetString("error_loadcolors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a max amount of 1 button (Discord Limitations).
        /// </summary>
        public static string error_max1discord {
            get {
                return ResourceManager.GetString("error_max1discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented yet.
        /// </summary>
        public static string error_notimplemented {
            get {
                return ResourceManager.GetString("error_notimplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred
        ///&apos;{0}&apos;
        ///Try to download the latest version from github, if it didn&apos;t help create a bug report with the error log attached..
        /// </summary>
        public static string error_startup {
            get {
                return ResourceManager.GetString("error_startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam is running, please close it and restart the app.
        /// </summary>
        public static string error_steamrunning {
            get {
                return ResourceManager.GetString("error_steamrunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error when sending the Telegram message, make sure your chat id is correct.
        /// </summary>
        public static string error_telegrammessage {
            get {
                return ResourceManager.GetString("error_telegrammessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t check for updates. Try again later.
        /// </summary>
        public static string error_update {
            get {
                return ResourceManager.GetString("error_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find CS:GO directory.
        /// </summary>
        public static string exception_csgonotfound {
            get {
                return ResourceManager.GetString("exception_csgonotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No network adapters with an IPv4 address in the system!.
        /// </summary>
        public static string exception_nonetworkadapter {
            get {
                return ResourceManager.GetString("exception_nonetworkadapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find Steam Path.
        /// </summary>
        public static string exception_steamnotfound {
            get {
                return ResourceManager.GetString("exception_steamnotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully imported file at &apos;{0}&apos;.
        /// </summary>
        public static string file_importsucess {
            get {
                return ResourceManager.GetString("file_importsucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved file at &apos;{0}&apos;.
        /// </summary>
        public static string file_savesucess {
            get {
                return ResourceManager.GetString("file_savesucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Link.
        /// </summary>
        public static string inputtext_botlinkbutton {
            get {
                return ResourceManager.GetString("inputtext_botlinkbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your desired label.
        /// </summary>
        public static string inputtext_enterlabel {
            get {
                return ResourceManager.GetString("inputtext_enterlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your desired URL.
        /// </summary>
        public static string inputtext_enterurl {
            get {
                return ResourceManager.GetString("inputtext_enterurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Label.
        /// </summary>
        public static string inputtext_label {
            get {
                return ResourceManager.GetString("inputtext_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Link.
        /// </summary>
        public static string inputtext_linkbutton {
            get {
                return ResourceManager.GetString("inputtext_linkbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the IP address you see in the app:.
        /// </summary>
        public static string inputtext_mobileip {
            get {
                return ResourceManager.GetString("inputtext_mobileip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Steam Web API Key.
        /// </summary>
        public static string inputtext_steamkey {
            get {
                return ResourceManager.GetString("inputtext_steamkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Telegram chat id, use the faq if you dont know how.
        /// </summary>
        public static string inputtext_telegramid {
            get {
                return ResourceManager.GetString("inputtext_telegramid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send test message.
        /// </summary>
        public static string inputtext_testmessagetelegram {
            get {
                return ResourceManager.GetString("inputtext_testmessagetelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter URL.
        /// </summary>
        public static string inputtext_url {
            get {
                return ResourceManager.GetString("inputtext_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone IP Address.
        /// </summary>
        public static string inputtitle_mobileip {
            get {
                return ResourceManager.GetString("inputtitle_mobileip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Web API Key.
        /// </summary>
        public static string inputtitle_steamkey {
            get {
                return ResourceManager.GetString("inputtitle_steamkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Telegram Bot Token.
        /// </summary>
        public static string inputtitle_telegramcustomtoken {
            get {
                return ResourceManager.GetString("inputtitle_telegramcustomtoken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram ID.
        /// </summary>
        public static string inputtitle_telegramid {
            get {
                return ResourceManager.GetString("inputtitle_telegramid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string language_en_US {
            get {
                return ResourceManager.GetString("language_en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrew.
        /// </summary>
        public static string language_he_IL {
            get {
                return ResourceManager.GetString("language_he-IL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string language_it_IT {
            get {
                return ResourceManager.GetString("language_it-IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        public static string language_ko_KR {
            get {
                return ResourceManager.GetString("language_ko-KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string language_ru_RU {
            get {
                return ResourceManager.GetString("language_ru-RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string menu_about {
            get {
                return ResourceManager.GetString("menu_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted match.
        /// </summary>
        public static string menu_acceptednotification {
            get {
                return ResourceManager.GetString("menu_acceptednotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Locations.
        /// </summary>
        public static string menu_alternativelocations {
            get {
                return ResourceManager.GetString("menu_alternativelocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Accept Match.
        /// </summary>
        public static string menu_autoaccept {
            get {
                return ResourceManager.GetString("menu_autoaccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Buy.
        /// </summary>
        public static string menu_autobuy {
            get {
                return ResourceManager.GetString("menu_autobuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Buy Armor.
        /// </summary>
        public static string menu_autobuyarmor {
            get {
                return ResourceManager.GetString("menu_autobuyarmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Buy Defuse Kit.
        /// </summary>
        public static string menu_autobuydefuse {
            get {
                return ResourceManager.GetString("menu_autobuydefuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates on startup.
        /// </summary>
        public static string menu_autocheckforupdates {
            get {
                return ResourceManager.GetString("menu_autocheckforupdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Check For Updates.
        /// </summary>
        public static string menu_autocheckupdates {
            get {
                return ResourceManager.GetString("menu_autocheckupdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close CSAuto when exiting CS2.
        /// </summary>
        public static string menu_autoclosecsauto {
            get {
                return ResourceManager.GetString("menu_autoclosecsauto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to focus on cs window when game is found.
        /// </summary>
        public static string menu_autofocus {
            get {
                return ResourceManager.GetString("menu_autofocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automation.
        /// </summary>
        public static string menu_automation {
            get {
                return ResourceManager.GetString("menu_automation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Reload.
        /// </summary>
        public static string menu_autoreload {
            get {
                return ResourceManager.GetString("menu_autoreload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Pause/Resume media.
        /// </summary>
        public static string menu_autospotify {
            get {
                return ResourceManager.GetString("menu_autospotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bomb information.
        /// </summary>
        public static string menu_bombnotification {
            get {
                return ResourceManager.GetString("menu_bombnotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        public static string menu_changelog {
            get {
                return ResourceManager.GetString("menu_changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string menu_checkforupdates {
            get {
                return ResourceManager.GetString("menu_checkforupdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer connected.
        /// </summary>
        public static string menu_connectednotification {
            get {
                return ResourceManager.GetString("menu_connectednotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Spraying.
        /// </summary>
        public static string menu_continuespray {
            get {
                return ResourceManager.GetString("menu_continuespray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game crashed.
        /// </summary>
        public static string menu_crashednotification {
            get {
                return ResourceManager.GetString("menu_crashednotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme.
        /// </summary>
        public static string menu_darktheme {
            get {
                return ResourceManager.GetString("menu_darktheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string menu_debug {
            get {
                return ResourceManager.GetString("menu_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord.
        /// </summary>
        public static string menu_discord {
            get {
                return ResourceManager.GetString("menu_discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord RPC Buttons.
        /// </summary>
        public static string menu_discordbuttons {
            get {
                return ResourceManager.GetString("menu_discordbuttons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Game RPC.
        /// </summary>
        public static string menu_discordingame {
            get {
                return ResourceManager.GetString("menu_discordingame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lobby RPC.
        /// </summary>
        public static string menu_discordlobby {
            get {
                return ResourceManager.GetString("menu_discordlobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord RPC.
        /// </summary>
        public static string menu_discordrpc {
            get {
                return ResourceManager.GetString("menu_discordrpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string menu_enabled {
            get {
                return ResourceManager.GetString("menu_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter IP address.
        /// </summary>
        public static string menu_enterip {
            get {
                return ResourceManager.GetString("menu_enterip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Steam Web API Key.
        /// </summary>
        public static string menu_entersteamkey {
            get {
                return ResourceManager.GetString("menu_entersteamkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Telegram Chat ID.
        /// </summary>
        public static string menu_entertelegramid {
            get {
                return ResourceManager.GetString("menu_entertelegramid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string menu_exit {
            get {
                return ResourceManager.GetString("menu_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus back to original window on accept.
        /// </summary>
        public static string menu_focusback {
            get {
                return ResourceManager.GetString("menu_focusback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string menu_general {
            get {
                return ResourceManager.GetString("menu_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string menu_language {
            get {
                return ResourceManager.GetString("menu_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch CS2.
        /// </summary>
        public static string menu_launchcs {
            get {
                return ResourceManager.GetString("menu_launchcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show players lobby count.
        /// </summary>
        public static string menu_lobbycount {
            get {
                return ResourceManager.GetString("menu_lobbycount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded in lobby.
        /// </summary>
        public static string menu_lobbynotification {
            get {
                return ResourceManager.GetString("menu_lobbynotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded on map.
        /// </summary>
        public static string menu_mapnotification {
            get {
                return ResourceManager.GetString("menu_mapnotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone notifications.
        /// </summary>
        public static string menu_mobile {
            get {
                return ResourceManager.GetString("menu_mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile App Notifications Enabled.
        /// </summary>
        public static string menu_mobileappenabled {
            get {
                return ResourceManager.GetString("menu_mobileappenabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string menu_notifications {
            get {
                return ResourceManager.GetString("menu_notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Chat/Console before auto buy.
        /// </summary>
        public static string menu_oldautobuy {
            get {
                return ResourceManager.GetString("menu_oldautobuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string menu_open {
            get {
                return ResourceManager.GetString("menu_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Debug Window.
        /// </summary>
        public static string menu_opendebug {
            get {
                return ResourceManager.GetString("menu_opendebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string menu_options {
            get {
                return ResourceManager.GetString("menu_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export settings.
        /// </summary>
        public static string menu_optionsexport {
            get {
                return ResourceManager.GetString("menu_optionsexport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import settings.
        /// </summary>
        public static string menu_optionsimport {
            get {
                return ResourceManager.GetString("menu_optionsimport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Mode.
        /// </summary>
        public static string menu_portablemode {
            get {
                return ResourceManager.GetString("menu_portablemode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer armor.
        /// </summary>
        public static string menu_preferarmor {
            get {
                return ResourceManager.GetString("menu_preferarmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Frames.
        /// </summary>
        public static string menu_savedebugframes {
            get {
                return ResourceManager.GetString("menu_savedebugframes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Logs.
        /// </summary>
        public static string menu_savedebuglogs {
            get {
                return ResourceManager.GetString("menu_savedebuglogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send capture to telegram on accept.
        /// </summary>
        public static string menu_sendacceptbutton {
            get {
                return ResourceManager.GetString("menu_sendacceptbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string menu_server {
            get {
                return ResourceManager.GetString("menu_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start With Windows.
        /// </summary>
        public static string menu_startup {
            get {
                return ResourceManager.GetString("menu_startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string menu_website {
            get {
                return ResourceManager.GetString("menu_website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A display that supports HDR has been found, the current settings are not optimized for HDR displays, do you want to optimize the settings?.
        /// </summary>
        public static string msgbox_hdroptimization {
            get {
                return ResourceManager.GetString("msgbox_hdroptimization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the latest version!.
        /// </summary>
        public static string msgbox_latestversion {
            get {
                return ResourceManager.GetString("msgbox_latestversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found newer verison ({0}) would you like to download it?.
        /// </summary>
        public static string msgbox_newerversion {
            get {
                return ResourceManager.GetString("msgbox_newerversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must restart the program to apply these changes.
        /// </summary>
        public static string msgbox_restartneeded {
            get {
                return ResourceManager.GetString("msgbox_restartneeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted a match!.
        /// </summary>
        public static string server_acceptmatch {
            get {
                return ResourceManager.GetString("server_acceptmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bomb has been defused.
        /// </summary>
        public static string server_bombdefuse {
            get {
                return ResourceManager.GetString("server_bombdefuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bomb exploded.
        /// </summary>
        public static string server_bombexplode {
            get {
                return ResourceManager.GetString("server_bombexplode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bomb has been planted.
        /// </summary>
        public static string server_bombplanted {
            get {
                return ResourceManager.GetString("server_bombplanted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer {0} ({1}) is online (CSAuto v{2}).
        /// </summary>
        public static string server_computeronline {
            get {
                return ResourceManager.GetString("server_computeronline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game crashed!.
        /// </summary>
        public static string server_gamecrash {
            get {
                return ResourceManager.GetString("server_gamecrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded in lobby!.
        /// </summary>
        public static string server_loadedlobby {
            get {
                return ResourceManager.GetString("server_loadedlobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded on map {0} in mode {1}.
        /// </summary>
        public static string server_loadedmap {
            get {
                return ResourceManager.GetString("server_loadedmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bomb seconds left:.
        /// </summary>
        public static string server_timeleft {
            get {
                return ResourceManager.GetString("server_timeleft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter-Terrorist.
        /// </summary>
        public static string team_ct {
            get {
                return ResourceManager.GetString("team_ct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrorist.
        /// </summary>
        public static string team_t {
            get {
                return ResourceManager.GetString("team_t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter-Strike 2 companion that automates in-game tasks, such as accepting match, buying items and more.
        /// </summary>
        public static string text_description {
            get {
                return ResourceManager.GetString("text_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string text_enabled {
            get {
                return ResourceManager.GetString("text_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority (the lower, the more chance it will be bought).
        /// </summary>
        public static string text_itempriority {
            get {
                return ResourceManager.GetString("text_itempriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected item:.
        /// </summary>
        public static string text_selecteditem {
            get {
                return ResourceManager.GetString("text_selecteditem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color: .
        /// </summary>
        public static string title_color {
            get {
                return ResourceManager.GetString("title_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details template.
        /// </summary>
        public static string title_discorddetails {
            get {
                return ResourceManager.GetString("title_discorddetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates:.
        /// </summary>
        public static string title_discordrpctemplates {
            get {
                return ResourceManager.GetString("title_discordrpctemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State template.
        /// </summary>
        public static string title_discordstate {
            get {
                return ResourceManager.GetString("title_discordstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string title_error {
            get {
                return ResourceManager.GetString("title_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimization.
        /// </summary>
        public static string title_optimization {
            get {
                return ResourceManager.GetString("title_optimization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuy.
        /// </summary>
        public static string title_rebuy {
            get {
                return ResourceManager.GetString("title_rebuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart app.
        /// </summary>
        public static string title_restartneeded {
            get {
                return ResourceManager.GetString("title_restartneeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients:.
        /// </summary>
        public static string title_serverclients {
            get {
                return ResourceManager.GetString("title_serverclients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port: .
        /// </summary>
        public static string title_serverport {
            get {
                return ResourceManager.GetString("title_serverport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string title_success {
            get {
                return ResourceManager.GetString("title_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates (CSAuto).
        /// </summary>
        public static string title_update {
            get {
                return ResourceManager.GetString("title_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string title_warning {
            get {
                return ResourceManager.GetString("title_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join the Discord server.
        /// </summary>
        public static string tooltip_discord {
            get {
                return ResourceManager.GetString("tooltip_discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the GitHub repository.
        /// </summary>
        public static string tooltip_github {
            get {
                return ResourceManager.GetString("tooltip_github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter here your bot token which will send you messages, if the token is wrong or doesn&apos;t exist the app will fallback to the default token.
        /// </summary>
        public static string tooltip_telegramcustomtoken {
            get {
                return ResourceManager.GetString("tooltip_telegramcustomtoken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified language was not found, app fallbacked to using English.
        /// </summary>
        public static string warning_language {
            get {
                return ResourceManager.GetString("warning_language", resourceCulture);
            }
        }
    }
}
