//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSAuto.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class DebugSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static DebugSettings defaultInstance = ((DebugSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DebugSettings())));
        
        public static DebugSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool pressAcceptButton {
            get {
                return ((bool)(this["pressAcceptButton"]));
            }
            set {
                this["pressAcceptButton"] = value;
            }
        }
    }
}
