//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSAuto.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSAuto.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ar_baggage,ar_dizzy,ar_lunacy,ar_monastery,ar_shoots,coop_kasbah,cs_agency,cs_assault,cs_insertion,cs_italy,cs_militia,cs_office,cs_workout,de_abbey,de_ancient,de_anubis,de_austria,de_aztec,de_bank,de_biome,de_breach,de_cache,de_canals,de_cbble,de_chlorine,de_dust,de_dust2,de_inferno,de_lake,de_mirage,de_mutiny,de_nuke,de_overpass,de_ruby,de_safehouse,de_seaside,de_shipped,de_shortdust,de_shortnuke,de_stmarc,de_studio,de_subzero,de_sugarcane,de_swamp,de_train,de_vertigo,de_zoo,dz_blacksite,dz_junglety,gd_cb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AVAILABLE_MAPS_STRING {
            get {
                return ResourceManager.GetString("AVAILABLE_MAPS_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Red&quot;, &quot;Green&quot;, &quot;Blue&quot;, &quot;Purple&quot;, &quot;Orange&quot;, &quot;Lime&quot;, &quot;Emerald&quot;, &quot;Teal&quot;, &quot;Cyan&quot;, &quot;Cobalt&quot;, &quot;Indigo&quot;, &quot;Violet&quot;, &quot;Pink&quot;, &quot;Magenta&quot;, &quot;Crimson&quot;, &quot;Amber&quot;, &quot;Yellow&quot;, &quot;Brown&quot;, &quot;Olive&quot;, &quot;Steel&quot;, &quot;Mauve&quot;, &quot;Taupe&quot;, &quot;Sienna&quot;.
        /// </summary>
        internal static string AVAILABLE_THEME_COLORS {
            get {
                return ResourceManager.GetString("AVAILABLE_THEME_COLORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;provider&quot;: {
        ///		&quot;name&quot;: &quot;Counter-Strike: Global Offensive&quot;,
        ///		&quot;appid&quot;: 730,
        ///		&quot;version&quot;: 13879,
        ///		&quot;steamid&quot;: &quot;76561198341800115&quot;,
        ///		&quot;timestamp&quot;: 1692506622
        ///	},
        ///	&quot;map&quot;: {
        ///		&quot;mode&quot;: &quot;competitive&quot;,
        ///		&quot;name&quot;: &quot;de_mirage&quot;,
        ///		&quot;phase&quot;: &quot;live&quot;,
        ///		&quot;round&quot;: 0,
        ///		&quot;team_ct&quot;: {
        ///			&quot;score&quot;: 0,
        ///			&quot;consecutive_round_losses&quot;: 1,
        ///			&quot;timeouts_remaining&quot;: 1,
        ///			&quot;matches_won_this_series&quot;: 0
        ///		},
        ///		&quot;team_t&quot;: {
        ///			&quot;score&quot;: 0,
        ///			&quot;name&quot;: &quot;wat doink&quot;,
        ///			&quot;consecutive_round_losses&quot;: 1,
        ///			&quot;timeouts_remaining&quot;: 1,
        ///			&quot;matches_wo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GAMESTATE_EXAMPLE {
            get {
                return ResourceManager.GetString("GAMESTATE_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon main {
            get {
                object obj = ResourceManager.GetObject("main", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
