//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSAuto.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool runAtStartUp {
            get {
                return ((bool)(this["runAtStartUp"]));
            }
            set {
                this["runAtStartUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool saveDebugFrames {
            get {
                return ((bool)(this["saveDebugFrames"]));
            }
            set {
                this["saveDebugFrames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool autoAcceptMatch {
            get {
                return ((bool)(this["autoAcceptMatch"]));
            }
            set {
                this["autoAcceptMatch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool autoReload {
            get {
                return ((bool)(this["autoReload"]));
            }
            set {
                this["autoReload"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool preferArmor {
            get {
                return ((bool)(this["preferArmor"]));
            }
            set {
                this["preferArmor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool autoBuyDefuseKit {
            get {
                return ((bool)(this["autoBuyDefuseKit"]));
            }
            set {
                this["autoBuyDefuseKit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool autoBuyArmor {
            get {
                return ((bool)(this["autoBuyArmor"]));
            }
            set {
                this["autoBuyArmor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool saveLogs {
            get {
                return ((bool)(this["saveLogs"]));
            }
            set {
                this["saveLogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ContinueSpraying {
            get {
                return ((bool)(this["ContinueSpraying"]));
            }
            set {
                this["ContinueSpraying"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoPausePlaySpotify {
            get {
                return ((bool)(this["autoPausePlaySpotify"]));
            }
            set {
                this["autoPausePlaySpotify"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool autoCheckForUpdates {
            get {
                return ((bool)(this["autoCheckForUpdates"]));
            }
            set {
                this["autoCheckForUpdates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enableDiscordRPC {
            get {
                return ((bool)(this["enableDiscordRPC"]));
            }
            set {
                this["enableDiscordRPC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string phoneIpAddress {
            get {
                return ((string)(this["phoneIpAddress"]));
            }
            set {
                this["phoneIpAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mobileAppEnabled {
            get {
                return ((bool)(this["mobileAppEnabled"]));
            }
            set {
                this["mobileAppEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("language_english")]
        public string currentLanguage {
            get {
                return ((string)(this["currentLanguage"]));
            }
            set {
                this["currentLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool acceptedNotification {
            get {
                return ((bool)(this["acceptedNotification"]));
            }
            set {
                this["acceptedNotification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mapNotification {
            get {
                return ((bool)(this["mapNotification"]));
            }
            set {
                this["mapNotification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool lobbyNotification {
            get {
                return ((bool)(this["lobbyNotification"]));
            }
            set {
                this["lobbyNotification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool connectedNotification {
            get {
                return ((bool)(this["connectedNotification"]));
            }
            set {
                this["connectedNotification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool crashedNotification {
            get {
                return ((bool)(this["crashedNotification"]));
            }
            set {
                this["crashedNotification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bombNotification {
            get {
                return ((bool)(this["bombNotification"]));
            }
            set {
                this["bombNotification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string steamAPIkey {
            get {
                return ((string)(this["steamAPIkey"]));
            }
            set {
                this["steamAPIkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool enableLobbyCount {
            get {
                return ((bool)(this["enableLobbyCount"]));
            }
            set {
                this["enableLobbyCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string telegramChatId {
            get {
                return ((string)(this["telegramChatId"]));
            }
            set {
                this["telegramChatId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool darkTheme {
            get {
                return ((bool)(this["darkTheme"]));
            }
            set {
                this["darkTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public string currentColor {
            get {
                return ((string)(this["currentColor"]));
            }
            set {
                this["currentColor"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>Red</string>
  <string>Green</string>
  <string>Blue</string>
  <string>Purple</string>
  <string>Orange</string>
  <string>Lime</string>
  <string>Emerald</string>
  <string>Teal</string>
  <string>Cyan</string>
  <string>Cobalt</string>
  <string>Indigo</string>
  <string>Violet</string>
  <string>Pink</string>
  <string>Magenta</string>
  <string>Crimson</string>
  <string>Amber</string>
  <string>Yellow</string>
  <string>Brown</string>
  <string>Olive</string>
  <string>Steel</string>
  <string>Mauve</string>
  <string>Taupe</string>
  <string>Sienna</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection availableColors {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["availableColors"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FriendCode: {FriendCode}")]
        public string lobbyDetails {
            get {
                return ((string)(this["lobbyDetails"]));
            }
            set {
                this["lobbyDetails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chilling in lobby")]
        public string lobbyState {
            get {
                return ((string)(this["lobbyState"]));
            }
            set {
                this["lobbyState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{Gamemode} - {Map}")]
        public string inGameDetails {
            get {
                return ((string)(this["inGameDetails"]));
            }
            set {
                this["inGameDetails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{TeamScore} [{MyTeam}] ({RoundState}) {EnemyScore} [{EnemyTeam}]")]
        public string inGameState {
            get {
                return ((string)(this["inGameState"]));
            }
            set {
                this["inGameState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool oldAutoBuy {
            get {
                return ((bool)(this["oldAutoBuy"]));
            }
            set {
                this["oldAutoBuy"] = value;
            }
        }
    }
}
