name: Update Changelog & Version

on:
  release:
   types:
      - published
      - deleted
  workflow_dispatch:
    inputs:
      skip_version:
        type: choice
        required: true
        description: "Update version?"
        default: 'yes'
        options:
          - yes
          - no

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Generate FullChangelog.MD
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: python scripts/full_changelog.py
    - name: Generate version
      if: ${{ github.event_name != 'workflow_dispatch' || inputs.skip_version == 'true' || inputs.skip_version == true }}
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: python scripts/version.py
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        add: 'Docs Data'
        message: 'chore(ci): update full changelog and version'
        default_author: github_actions
        push: true
        new_branch: 'master'
