name: Batch File Continuous Integration
on:
    push:
        tags:
            - "v*.*.*"
# Can have multiple jobs, but this example is just one build job.
jobs:
    build:
        permissions: write-all
        runs-on: windows-latest
        steps:
        
          # 1. Check out repository to current directory.
          - name: Checkout Files
            uses: actions/checkout@v3
            
          # 2. Use cmd shell to build the batch file, parameters may be passed to it,
          #    and if it exits with ERRORLEVEL != 0 it will halt.
          #    The text output from the batch file will be in the log.
          - name: Build ROM
            shell: cmd
            run: compile.bat
         - name: Release
            uses: softprops/action-gh-release@v1
            with:
              files: |
                Output/CSAuto_Portable.zip
                Output/CSAuto_Installer.exe
                Output/CSAuto_Android.apk